language: minimal

before_script:
  - sudo apt-get install -qq libxml2-utils xsltproc asciidoctor

script:
  - bash .travis/xmllint-check.sh && bash docs/check-ojp-schemas.sh && bash docs/generate-tables.sh

after_script:
  - bash .travis/travis-ci_git-commit.sh
